name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./mjpg-streamer-experimental
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_1
      run: sudo apt-get install cmake libjpeg8
    - name: install_2
      run: sudo apt-get install gcc g++
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
