name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_1
      run: sudo apt-get install cmake libjpeg8
    - name: install_2
      run: sudo apt-get install gcc g++
    - name: cd workdir
      run : cd ./mjpg-streamer-experimental
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
