name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./mjpg-streamer-experimental
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_1
      run: sudo apt-get install cmake libjpeg8
    - name: install_2
      run: sudo apt-get install gcc g++
    - name: install_3
      run: sudo apt-get install dpkg debconf debhelper lintian checkinstall
    - name: make
      run: make
    - name: ls
      run: |
       ls -la
       ls -la _build
    - name: Creating out
      run: | 
        mkdir out
        cp -r _build/* out
        ls -la
    - name: Upload build 
      uses: actions/upload-artifact@master 
      with: 
         name: linux 
         path: out
